package model

type AvatarInfo struct {
	AvatarID              int                `json:"avatarId"`
	TalentIdList          []int              `json:"talentIdList,omitempty"`
	PropMap               map[string]Prop    `json:"propMap"`
	FightProp             map[string]float64 `json:"fightProp"`
	SkillDepotId          int                `json:"skillDepotId"`
	InheritProudSkillList []int              `json:"inheritProudSkillList"`
	SkillLevelMap         map[string]int     `json:"skillLevelMap"`
	EquipList             []Equip            `json:"equipList"`
	FetterInfo            map[string]int     `json:"fetterInfo"`
}

type Prop struct {
	Type int    `json:"type"`
	Ival string `json:"ival"`
	Val  string `json:"val"`
}

const (
	PROP_TYPE_XP        = "1001"
	PROP_TYPE_ASCENSION = "1002"
	PROP_TYPE_LEVEL     = "4001"
)

const (
	FIGHTPROP_TYPE_BASE_HP                = "1"
	FIGHTPROP_TYPE_HP                     = "2"
	FIGHTPROP_TYPR_HP_PERCENTAGE          = "3"
	FIGHTPROP_TYPE_BASE_ATK               = "4"
	FIGHTPROP_TYPE_ATK                    = "5"
	FIGHTPROP_TYPE_ATK_PERCENTAGE         = "6"
	FIGHTPROP_TYPE_BASE_DEF               = "7"
	FIGHTPROP_TYPE_DEF                    = "8"
	FIGHTPROP_TYPE_DEF_PERCENTAGE         = "9"
	FIGHTPROP_TYPE_BASE_SPD               = "10"
	FIGHTPROP_TYPE_SPD_PERCENTAGE         = "11"
	FIGHTPROP_TYPE_CRIT_RATE              = "20"
	FIGHTPROP_TYPE_CRIT_DAMAGE            = "22"
	FIGHTPROP_TYPE_ENERGY_RECHARGE        = "23"
	FIGHTPROP_TYPE_HEALING_BONUS          = "26"
	FIGHTPROP_TYPE_INCOMING_HEALING_BONUS = "27"
	FIGHTPROP_TYPE_ELEMENTAL_MASTERY      = "28"
	FIGHTPROP_TYPE_PHYSICAL_RES           = "29"
	FIGHTPROP_TYPE_PHYSICAL_DAMAGE_BONUS  = "30"
	FIGHTPROP_TYPE_PYRO_DAMAGE_BONUS      = "40"
	FIGHTPROP_TYPE_ElECTRO_DAMAGE_BONUS   = "41"
	FIGHTPROP_TYPE_HYDRO_DAMAGE_BONUS     = "42"
	FIGHTPROP_TYPE_DENDRO_DAMAGE_BONUS    = "43"
	FIGHTPROP_TYPE_ANEMO_DAMAGE_BONUS     = "44"
	FIGHTPROP_TYPE_GEO_DAMAGE_BONUS       = "45"
	FIGHTPROP_TYPE_CRYO_DAMAGE_BONUS      = "46"
	FIGHTPROP_TYPE_PYRO_RES               = "50"
	FIGHTPROP_TYPE_ElECTRO_RES            = "51"
	FIGHTPROP_TYPE_HYDRO_RES              = "52"
	FIGHTPROP_TYPE_DENDRO_RES             = "53"
	FIGHTPROP_TYPE_ANEMO_RES              = "54"
	FIGHTPROP_TYPE_GEO_RES                = "55"
	FIGHTPROP_TYPE_CRYO_RES               = "56"
	FIGHTPROP_TYPE_PYRO_ENERGY_CAST       = "70"
	FIGHTPROP_TYPE_ElECTRO_ENERGY_CAST    = "71"
	FIGHTPROP_TYPE_HYDRO_ENERGY_CAST      = "72"
	FIGHTPROP_TYPE_DENDRO_ENERGY_CAST     = "73"
	FIGHTPROP_TYPE_ANEMO_ENERGY_CAST      = "74"
	FIGHTPROP_TYPE_CRYO_ENERGY_CAST       = "75"
	FIGHTPROP_TYPE_GEO_ENERGY_CAST        = "76"
	FIGHTPROP_TYPE_COOLDOWN_REDUCTION     = "80"
	FIGHTPROP_TYPE_SHIELD_STRENGTH        = "81"

	FIGHTPROP_TYPE_CURRENT_PYRO_ENERGY    = "1000"
	FIGHTPROP_TYPE_CURRENT_ElECTRO_ENERGY = "1001"
	FIGHTPROP_TYPE_CURRENT_HYDRO_ENERGY   = "1002"
	FIGHTPROP_TYPE_CURRENT_DENDRO_ENERGY  = "1003"
	FIGHTPROP_TYPE_CURRENT_ANEMO_ENERGY   = "1004"
	FIGHTPROP_TYPE_CURRENT_CRYO_ENERGY    = "1005"
	FIGHTPROP_TYPE_CURRENT_GEO_ENERGY     = "1006"
	FIGHTPROP_TYPE_CURRENT_HP             = "1010"

	FIGHTPROP_TYPE_MAX_HP  = "2000"
	FIGHTPROP_TYPE_MAX_ATK = "2001"
	FIGHTPROP_TYPE_MAX_DEF = "2002"
	FIGHTPROP_TYPE_MAX_SPD = "2003"

	FIGHTPROP_TYPE_ELEMENTAL_REACTION_CRIT_RATE                    = "3025"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_CRIT_DAMAGE                  = "3026"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_OVERLOADED_CRIT_RATE         = "3027"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_OVERLOADED_CRIT_DAMAGE       = "3028"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_SWIRL_CRIT_RATE              = "3029"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_SWIRL_CRIT_DAMAGE            = "3030"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_ELECTRO_CHARGED_CRIT_RATE    = "3031"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_ELECTRO_CHARGED_CRIT_DAMAGE  = "3032"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_SUPERCONDUCT_CRIT_RATE       = "3033"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_SUPERCONDUCT_CRIT_DAMAGE     = "3034"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_BURN_CRIT_RATE               = "3035"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_BURN_CRIT_DAMAGE             = "3036"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_FROZEN_SHATTERED_CRIT_RATE   = "3037"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_FROZEN_SHATTERED_CRIT_DAMAGE = "3038"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_BLOOM_CRIT_RATE              = "3039"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_BLOOM_CRIT_DAMAGE            = "3040"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_BURGEON_CRIT_RATE            = "3041"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_BURGEON_CRIT_DAMAGE          = "3042"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_HYPERBLOOM_CRIT_RATE         = "3043"
	FIGHTPROP_TYPE_ELEMENTAL_REACTION_HYPERBLOOM_CRIT_DAMAGE       = "3044"
	FIGHTPROP_TYPE_BASE_ELEMENTAL_REACTION_CRIT_RATE               = "3045"
	FIGHTPROP_TYPE_BASE_ELEMENTAL_REACTION_CRIT_DAMAGE             = "3046"
)
